# MongoDB 101

<img src="https://cdn.meme.am/images/11599433.jpg" alt="Title" style="width:350px"/>

## Welcome to MongoDB 101! Let's take a look at what we need to do today.
#### Step 1
* Log into https://mlab.com/ and create an account
* Create database within your account
* Create two users. One with read-only permissions. One without read-only permissions
* Follow the instructions below when you are ready

In [2]:
from pymongo import MongoClient

#This is the client. Replace my (username) and (password) with your non-readonly username and password
client = MongoClient("mongodb://dnay:password123@ds031925.mlab.com:31925/naytest")
#We get the database here. Don't forget to change the db name to your database name!
db = client.naytest

In [3]:
test = db.test
print test
test.insert_one({'name': 'Dan','age':'28','color':'blue'})
test.find_one()

#to remove
# test.remove()
# test.remove({'color':'blue'})

Collection(Database(MongoClient(host=['ds031925.mlab.com:31925'], document_class=dict, tz_aware=False, connect=True), u'naytest'), u'test')

{u'_id': ObjectId('580f9f74496a9d059fc6f71b'),
 u'age': u'28',
 u'color': u'blue',
 u'name': u'Dan'}

## Navigate to wikipedia and pull down a table of your choice. Here is a sample of what I did to pull down the Harrison Ford movies table to help you out.

In [4]:
import urllib2
from bs4 import BeautifulSoup
import json
import pandas as pd

soup = BeautifulSoup(urllib2.urlopen('https://en.wikipedia.org/wiki/List_of_tallest_buildings', "lxml").read())
tables = soup.find_all('table', class_="wikitable")
listy = []
for idx, table in enumerate(tables):
    if idx == 1:
        for idx2, row in enumerate(table.find_all('tr')):
            datay = row.find_all('td')
            if len(datay) > 3:
                listy += [{'Rank':datay[0].text,'Name':datay[-7].text,'City':datay[-6].text, 'Country':datay[-5].text,
                         'Height in feet':datay[-4].text,'Height in meters':datay[-3].text, 'Floors':datay[-2].text}]
            #print row
tallest = pd.DataFrame(listy)
print tallest.head()

del tallest['Height in meters']
del tallest['Rank']

/Users/dnay/anaconda/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 174 of the file /Users/dnay/anaconda/lib/python2.7/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))

       City        Country Floors Height in feet Height in meters  \
0     Dubai            UAE    163       2,717 ft            828 m
1  Shanghai          China    128       2,073 ft        632 m[10]
2     Mecca   Saudi Arabia    120       1,971 ft        601 m[11]
3  Shenzhen          China    115       1,969 ft            600 m
4     Seoul    South Korea    123       1,823 ft            555 m

                        Name Rank
0               Burj Khalifa    1
1             Shanghai Tower    2
2  Abraj Al-Bait Clock Tower    3
3     Ping An Finance Centre    4
4          Lotte World Tower    5

In [5]:
listy

[{'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'163',
  'Height in feet': u'2,717\xa0ft',
  'Height in meters': u'828\xa0m',
  'Name': u'Burj Khalifa',
  'Rank': u'1'},
 {'City': u'Shanghai',
  'Country': u'\xa0China',
  'Floors': u'128',
  'Height in feet': u'2,073\xa0ft',
  'Height in meters': u'632\xa0m[10]',
  'Name': u'Shanghai Tower',
  'Rank': u'2'},
 {'City': u'Mecca',
  'Country': u'\xa0Saudi Arabia',
  'Floors': u'120',
  'Height in feet': u'1,971\xa0ft',
  'Height in meters': u'601\xa0m[11]',
  'Name': u'Abraj Al-Bait Clock Tower',
  'Rank': u'3'},
 {'City': u'Shenzhen',
  'Country': u'\xa0China',
  'Floors': u'115',
  'Height in feet': u'1,969\xa0ft',
  'Height in meters': u'600\xa0m',
  'Name': u'Ping An Finance Centre',
  'Rank': u'4'},
 {'City': u'Seoul',
  'Country': u'\xa0South Korea',
  'Floors': u'123',
  'Height in feet': u'1,823\xa0ft',
  'Height in meters': u'555\xa0m',
  'Name': u'Lotte World Tower',
  'Rank': u'5'},
 {'City': u'New York City',
  'Country': u'\xa0United States',
  'Floors': u'104',
  'Height in feet': u'1,776\xa0ft',
  'Height in meters': u'541\xa0m',
  'Name': u'One World Trade Center',
  'Rank': u'6'},
 {'City': u'Guangzhou',
  'Country': u'\xa0China',
  'Floors': u'111',
  'Height in feet': u'1,740\xa0ft',
  'Height in meters': u'530\xa0m[12]',
  'Name': u'CTF Finance Centre',
  'Rank': u'7'},
 {'City': u'Taipei',
  'Country': u'\xa0Taiwan',
  'Floors': u'101',
  'Height in feet': u'1,670\xa0ft',
  'Height in meters': u'509\xa0m[13]',
  'Name': u'Taipei 101',
  'Rank': u'8'},
 {'City': u'Shanghai',
  'Country': u'\xa0China',
  'Floors': u'101',
  'Height in feet': u'1,614\xa0ft',
  'Height in meters': u'492\xa0m',
  'Name': u'Shanghai World Financial Center',
  'Rank': u'9'},
 {'City': u'Hong Kong',
  'Country': u'\xa0Hong Kong',
  'Floors': u'118',
  'Height in feet': u'1,588\xa0ft',
  'Height in meters': u'484\xa0m',
  'Name': u'International Commerce Centre',
  'Rank': u'10'},
 {'City': u'Kuala Lumpur',
  'Country': u'\xa0Malaysia',
  'Floors': u'88',
  'Height in feet': u'1,483\xa0ft',
  'Height in meters': u'452\xa0m',
  'Name': u'Petronas Tower 1',
  'Rank': u'11'},
 {'City': u'Kuala Lumpur',
  'Country': u'\xa0Malaysia',
  'Floors': u'88',
  'Height in feet': u'1,483\xa0ft',
  'Height in meters': u'452\xa0m',
  'Name': u'Petronas Tower 2',
  'Rank': u'Petronas Tower 2'},
 {'City': u'Nanjing',
  'Country': u'\xa0China',
  'Floors': u'89',
  'Height in feet': u'1,476\xa0ft',
  'Height in meters': u'450\xa0m',
  'Name': u'Zifeng Tower',
  'Rank': u'13'},
 {'City': u'Chicago',
  'Country': u'\xa0United States',
  'Floors': u'108',
  'Height in feet': u'1,451\xa0ft\xa0',
  'Height in meters': u'442\xa0m',
  'Name': u'Willis Tower (formerly the Sears Tower)',
  'Rank': u'14'},
 {'City': u'Shenzhen',
  'Country': u'\xa0China',
  'Floors': u'100',
  'Height in feet': u'1,449\xa0ft',
  'Height in meters': u'442\xa0m',
  'Name': u'KK100',
  'Rank': u'15'},
 {'City': u'Guangzhou',
  'Country': u'\xa0China',
  'Floors': u'103',
  'Height in feet': u'1,440\xa0ft',
  'Height in meters': u'440\xa0m',
  'Name': u'Guangzhou International Finance Center',
  'Rank': u'16'},
 {'City': u'Wuhan',
  'Country': u'\xa0China',
  'Floors': u'88',
  'Height in feet': u'1,437\xa0ft',
  'Height in meters': u'438\xa0m',
  'Name': u'Wuhan Center',
  'Rank': u'17'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'101',
  'Height in feet': u'1,399\xa0ft',
  'Height in meters': u'427\xa0m',
  'Name': u'Marina 101',
  'Rank': u'18'},
 {'City': u'New York City',
  'Country': u'\xa0United States',
  'Floors': u'88',
  'Height in feet': u'1,397\xa0ft',
  'Height in meters': u'426\xa0m',
  'Name': u'432 Park Avenue',
  'Rank': u'19'},
 {'City': u'Chicago',
  'Country': u'\xa0United States',
  'Floors': u'98',
  'Height in feet': u'1,389\xa0ft',
  'Height in meters': u'423\xa0m',
  'Name': u'Trump International Hotel and Tower[14]',
  'Rank': u'20'},
 {'City': u'Shanghai',
  'Country': u'\xa0China',
  'Floors': u'88',
  'Height in feet': u'1,380\xa0ft',
  'Height in meters': u'421\xa0m',
  'Name': u'Jin Mao Tower',
  'Rank': u'21'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'101',
  'Height in feet': u'1,358\xa0ft[15]',
  'Height in meters': u'414\xa0m',
  'Name': u'Princess Tower',
  'Rank': u'22'},
 {'City': u'Kuwait City',
  'Country': u'\xa0Kuwait',
  'Floors': u'80',
  'Height in feet': u'1,354\xa0ft',
  'Height in meters': u'413\xa0m',
  'Name': u'Al Hamra Tower',
  'Rank': u'23'},
 {'City': u'Hong Kong',
  'Country': u'\xa0Hong Kong',
  'Floors': u'88',
  'Height in feet': u'1,352\xa0ft',
  'Height in meters': u'412\xa0m',
  'Name': u'Two International Finance Centre',
  'Rank': u'24'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'89',
  'Height in feet': u'1,296\xa0ft',
  'Height in meters': u'395\xa0m',
  'Name': u'23 Marina',
  'Rank': u'25'},
 {'City': u'Guangzhou',
  'Country': u'\xa0China',
  'Floors': u'80',
  'Height in feet': u'1,283\xa0ft',
  'Height in meters': u'391\xa0m',
  'Name': u'CITIC Plaza',
  'Rank': u'26'},
 {'City': u'Riyadh',
  'Country': u'\xa0Saudi Arabia',
  'Floors': u'77',
  'Height in feet': u'1,263\xa0ft',
  'Height in meters': u'385\xa0m',
  'Name': u'cma tower',
  'Rank': u'27'},
 {'City': u'Shenzhen',
  'Country': u'\xa0China',
  'Floors': u'69',
  'Height in feet': u'1,260\xa0ft',
  'Height in meters': u'384\xa0m',
  'Name': u'Shun Hing Square',
  'Rank': u'28'},
 {'City': u'Dalian',
  'Country': u'\xa0China',
  'Floors': u'81',
  'Height in feet': u'1,257\xa0ft',
  'Height in meters': u'383\xa0m',
  'Name': u'Eton Place Dalian Tower 1',
  'Rank': u'29'},
 {'City': u'Abu Dhabi',
  'Country': u'\xa0UAE',
  'Floors': u'88',
  'Height in feet': u'1,251\xa0ft',
  'Height in meters': u'381\xa0m',
  'Name': u'Burj Mohammed bin Rashid',
  'Rank': u'30'},
 {'City': u'New York City',
  'Country': u'\xa0United States',
  'Floors': u'102',
  'Height in feet': u'1,250\xa0ft',
  'Height in meters': u'381\xa0m',
  'Name': u'Empire State Building',
  'Rank': u'31'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'87',
  'Height in feet': u'1,248\xa0ft',
  'Height in meters': u'381\xa0m',
  'Name': u'Elite Residence',
  'Rank': u'32'},
 {'City': u'Hong Kong',
  'Country': u'\xa0Hong Kong',
  'Floors': u'78',
  'Height in feet': u'1,227\xa0ft',
  'Height in meters': u'374\xa0m',
  'Name': u'Central Plaza',
  'Rank': u'33'},
 {'City': u'Moscow',
  'Country': u'\xa0Russia',
  'Floors': u'95',
  'Height in feet': u'1,226\xa0ft',
  'Height in meters': u'374\xa0m',
  'Name': u'Federation Tower (East Tower)[16]',
  'Rank': u'34'},
 {'City': u'Dalian',
  'Country': u'\xa0China',
  'Floors': u'86',
  'Height in feet': u'1,214\xa0ft',
  'Height in meters': u'370\xa0m',
  'Name': u'Dalian International Trade Center',
  'Rank': u'35'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'72',
  'Height in feet': u'1,207\xa0ft',
  'Height in meters': u'368\xa0m',
  'Name': u'The Address the BLVD',
  'Rank': u'36'},
 {'City': u'Hong Kong',
  'Country': u'\xa0Hong Kong',
  'Floors': u'70',
  'Height in feet': u'1,205\xa0ft',
  'Height in meters': u'367\xa0m',
  'Name': u'Bank of China Tower',
  'Rank': u'37'},
 {'City': u'New York City',
  'Country': u'\xa0United States',
  'Floors': u'54',
  'Height in feet': u'1,200\xa0ft',
  'Height in meters': u'366\xa0m',
  'Name': u'Bank of America Tower',
  'Rank': u'38'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'68',
  'Height in feet': u'1,191\xa0ft',
  'Height in meters': u'363\xa0m',
  'Name': u'Almas Tower',
  'Rank': u'39'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'82',
  'Height in feet': u'1,166\xa0ft',
  'Height in meters': u'355\xa0m',
  'Name': u'JW Marriott Marquis Dubai Tower 1',
  'Rank': u'40'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'82',
  'Height in feet': u'1,166\xa0ft',
  'Height in meters': u'355\xa0m',
  'Name': u'Marquis Dubai Tower 2',
  'Rank': u'Marquis Dubai Tower 2'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'54',
  'Height in feet': u'1,163\xa0ft',
  'Height in meters': u'355\xa0m',
  'Name': u'Emirates Office Tower',
  'Rank': u'41'},
 {'City': u'Moscow',
  'Country': u'\xa0Russia',
  'Floors': u'85',
  'Height in feet': u'1,160\xa0ft',
  'Height in meters': u'354\xa0m',
  'Name': u'OKO Tower - South Tower',
  'Rank': u'42'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'86',
  'Height in feet': u'1,155\xa0ft',
  'Height in meters': u'352\xa0m',
  'Name': u'The Marina Torch',
  'Rank': u'43'},
 {'City': u'Shenyang',
  'Country': u'\xa0China',
  'Floors': u'68',
  'Height in feet': u'1,150\xa0ft',
  'Height in meters': u'351\xa0m',
  'Name': u'Forum 66 Tower 2',
  'Rank': u'44'},
 {'City': u'Guangzhou',
  'Country': u'\xa0China',
  'Floors': u'60',
  'Height in feet': u'1,149\xa0ft',
  'Height in meters': u'350\xa0m',
  'Name': u'The Pinnacle',
  'Rank': u'45'},
 {'City': u'Las Vegas',
  'Country': u'\xa0United States',
  'Floors': u'N/A',
  'Height in feet': u'1,149\xa0ft',
  'Height in meters': u'350\xa0m',
  'Name': u'Stratosphere Las Vegas',
  'Rank': u'Stratosphere Las Vegas'},
 {'City': u'Kaohsiung',
  'Country': u'\xa0Taiwan',
  'Floors': u'85',
  'Height in feet': u'1,140\xa0ft',
  'Height in meters': u'347\xa0m',
  'Name': u'Tuntex Sky Tower',
  'Rank': u'47'},
 {'City': u'Chicago',
  'Country': u'\xa0United States',
  'Floors': u'83',
  'Height in feet': u'1,136\xa0ft',
  'Height in meters': u'346\xa0m',
  'Name': u'Aon Center',
  'Rank': u'48'},
 {'City': u'Hong Kong',
  'Country': u'\xa0Hong Kong',
  'Floors': u'73',
  'Height in feet': u'1,135\xa0ft',
  'Height in meters': u'346\xa0m',
  'Name': u'The Center',
  'Rank': u'49'},
 {'City': u'Chicago',
  'Country': u'\xa0United States',
  'Floors': u'100',
  'Height in feet': u'1,128\xa0ft',
  'Height in meters': u'344\xa0m',
  'Name': u'John Hancock Center',
  'Rank': u'50'},
 {'City': u'Abu Dhabi',
  'Country': u'\xa0UAE',
  'Floors': u'76',
  'Height in feet': u'1,122\xa0ft',
  'Height in meters': u'342\xa0m',
  'Name': u'ADNOC Headquarters',
  'Rank': u'51'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'76',
  'Height in feet': u'1,122\xa0ft',
  'Height in meters': u'342\xa0m',
  'Name': u'Ahmed Abdul Rahim Al Attar Tower',
  'Rank': u'Ahmed Abdul Rahim Al Attar Tower'},
 {'City': u'Wuxi',
  'Country': u'\xa0China',
  'Floors': u'68',
  'Height in feet': u'1,112\xa0ft',
  'Height in meters': u'339\xa0m',
  'Name': u'The Wharf Times Square',
  'Rank': u'53'},
 {'City': u'Chongqing',
  'Country': u'\xa0China',
  'Floors': u'78',
  'Height in feet': u'1,112\xa0ft',
  'Height in meters': u'339\xa0m',
  'Name': u'Chongqing World Financial Center',
  'Rank': u'54'},
 {'City': u'Moscow',
  'Country': u'\xa0Russia',
  'Floors': u'75',
  'Height in feet': u'1,112\xa0ft',
  'Height in meters': u'339\xa0m',
  'Name': u'Mercury City Tower',
  'Rank': u'55'},
 {'City': u'Tianjin',
  'Country': u'\xa0China',
  'Floors': u'65',
  'Height in feet': u'1,109\xa0ft',
  'Height in meters': u'338\xa0m',
  'Name': u'Tianjin Modern City Office Tower',
  'Rank': u'56'},
 {'City': u'Tianjin',
  'Country': u'\xa0China',
  'Floors': u'79',
  'Height in feet': u'1,105\xa0ft',
  'Height in meters': u'337\xa0m',
  'Name': u'Tianjin World Financial Center',
  'Rank': u'57'},
 {'City': u'Guiyang',
  'Country': u'\xa0China',
  'Floors': u'74',
  'Height in feet': u'1,099\xa0ft',
  'Height in meters': u'335\xa0m',
  'Name': u'Twin Towers Guiyang, East Tower',
  'Rank': u'58'},
 {'City': u'Guiyang',
  'Country': u'\xa0China',
  'Floors': u'74',
  'Height in feet': u'1,099\xa0ft',
  'Height in meters': u'335\xa0m',
  'Name': u'Twin Towers Guiyang, West Tower',
  'Rank': u'Twin Towers Guiyang, West Tower'},
 {'City': u'Los Angeles',
  'Country': u'\xa0United States',
  'Floors': u'73',
  'Height in feet': u'1,099\xa0ft',
  'Height in meters': u'335\xa0m',
  'Name': u'Wilshire Grand Center',
  'Rank': u'60'},
 {'City': u'Shanghai',
  'Country': u'\xa0China',
  'Floors': u'61',
  'Height in feet': u'1,094\xa0ft',
  'Height in meters': u'333\xa0m',
  'Name': u'Shimao International Plaza',
  'Rank': u'61'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'72',
  'Height in feet': u'1,093\xa0ft',
  'Height in meters': u'333\xa0m',
  'Name': u'Rose Tower',
  'Rank': u'62'},
 {'City': u'Wuhan',
  'Country': u'\xa0China',
  'Floors': u'68',
  'Height in feet': u'1,087\xa0ft',
  'Height in meters': u'331\xa0m',
  'Name': u'Minsheng Bank Building',
  'Rank': u'63'},
 {'City': u'Beijing',
  'Country': u'\xa0China',
  'Floors': u'74',
  'Height in feet': u'1,083\xa0ft',
  'Height in meters': u'330\xa0m',
  'Name': u'China World Trade Center Tower 3',
  'Rank': u'64'},
 {'City': u'Pyongyang',
  'Country': u'\xa0North Korea',
  'Floors': u'105',
  'Height in feet': u'1,083\xa0ft',
  'Height in meters': u'330\xa0m',
  'Name': u'Ryugyong Hotel',
  'Rank': u'Ryugyong Hotel'},
 {'City': u'Zhuhai',
  'Country': u'\xa0China',
  'Floors': u'67',
  'Height in feet': u'1,083\xa0ft',
  'Height in meters': u'330\xa0m',
  'Name': u'Zhuhai St. Regis Hotel & Office Tower',
  'Rank': u'Zhuhai St. Regis Hotel & Office Tower'},
 {'City': u'Wuhan',
  'Country': u'\xa0China',
  'Floors': u'66',
  'Height in feet': u'1,083\xa0ft',
  'Height in meters': u'330\xa0m',
  'Name': u'Yuexiu Fortune Center Tower 1',
  'Rank': u'Yuexiu Fortune Center Tower 1'},
 {'City': u'Shenzhen',
  'Country': u'\xa0China',
  'Floors': u'80',
  'Height in feet': u'1,081\xa0ft',
  'Height in meters': u'329\xa0m',
  'Name': u'Hon Kwok City Center',
  'Rank': u'68'},
 {'City': u'Hanoi',
  'Country': u'\xa0Vietnam',
  'Floors': u'72',
  'Height in feet': u'1,078\xa0ft',
  'Height in meters': u'329\xa0m',
  'Name': u'Keangnam Hanoi Landmark Tower',
  'Rank': u'69'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'69',
  'Height in feet': u'1,076\xa0ft',
  'Height in meters': u'328\xa0m',
  'Name': u'Al Yaqoub Tower',
  'Rank': u'70'},
 {'City': u'Huaxi Village',
  'Country': u'\xa0China',
  'Floors': u'72',
  'Height in feet': u'1,076\xa0ft',
  'Height in meters': u'328\xa0m',
  'Name': u'Longxi International Hotel',
  'Rank': u'Longxi International Hotel'},
 {'City': u'Wuxi',
  'Country': u'\xa0China',
  'Floors': u'68',
  'Height in feet': u'1,076\xa0ft',
  'Height in meters': u'328\xa0m',
  'Name': u'Wuxi Suning Plaza 1',
  'Rank': u'Wuxi Suning Plaza 1'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'80',
  'Height in feet': u'1,070\xa0ft',
  'Height in meters': u'326\xa0m',
  'Name': u'The Index',
  'Rank': u'73'},
 {'City': u'Nanning',
  'Country': u'\xa0China',
  'Floors': u'68',
  'Height in feet': u'1,066\xa0ft',
  'Height in meters': u'325\xa0m',
  'Name': u'Guangxi Finance Plaza',
  'Rank': u'74'},
 {'City': u'Abu Dhabi',
  'Country': u'\xa0UAE',
  'Floors': u'72',
  'Height in feet': u'1,063\xa0ft',
  'Height in meters': u'324\xa0m',
  'Name': u'The Landmark',
  'Rank': u'75'},
 {'City': u'Nanjing',
  'Country': u'\xa0China',
  'Floors': u'62',
  'Height in feet': u'1,063\xa0ft',
  'Height in meters': u'324\xa0m',
  'Name': u'Deji Plaza Phase 2',
  'Rank': u'Deji Plaza Phase 2'},
 {'City': u'Yantai',
  'Country': u'\xa0China',
  'Floors': u'59',
  'Height in feet': u'1,060\xa0ft',
  'Height in meters': u'323\xa0m',
  'Name': u'Yantai Shimao No.1 The Harbour',
  'Rank': u'77'},
 {'City': u'Gold Coast',
  'Country': u'\xa0Australia',
  'Floors': u'80',
  'Height in feet': u'1,058\xa0ft',
  'Height in meters': u'323\xa0m',
  'Name': u'Q1',
  'Rank': u'78'},
 {'City': u'Wenzhou',
  'Country': u'\xa0China',
  'Floors': u'68',
  'Height in feet': u'1,056\xa0ft',
  'Height in meters': u'322\xa0m',
  'Name': u'Wenzhou World Trade Center',
  'Rank': u'79'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'60',
  'Height in feet': u'1,053\xa0ft',
  'Height in meters': u'321\xa0m',
  'Name': u'Burj Al Arab',
  'Rank': u'80'},
 {'City': u'Hong Kong',
  'Country': u'\xa0Hong Kong',
  'Floors': u'80',
  'Height in feet': u'1,051\xa0ft',
  'Height in meters': u'320\xa0m',
  'Name': u'Nina Tower',
  'Rank': u'81'},
 {'City': u'Shanghai',
  'Country': u'\xa0China',
  'Floors': u'66',
  'Height in feet': u'1,048\xa0ft',
  'Height in meters': u'320\xa0m',
  'Name': u'Sinar Mas Center 1',
  'Rank': u'82'},
 {'City': u'New York City',
  'Country': u'\xa0United States',
  'Floors': u'77',
  'Height in feet': u'1,046\xa0ft',
  'Height in meters': u'319\xa0m',
  'Name': u'Chrysler Building',
  'Rank': u'83'},
 {'City': u'Guangzhou',
  'Country': u'\xa0China',
  'Floors': u'67',
  'Height in feet': u'1,046\xa0ft',
  'Height in meters': u'319\xa0m',
  'Name': u'Global City Square[17]',
  'Rank': u'Global City Square[17]'},
 {'City': u'New York City',
  'Country': u'\xa0United States',
  'Floors': u'52',
  'Height in feet': u'1,046\xa0ft',
  'Height in meters': u'319\xa0m',
  'Name': u'New York Times Building',
  'Rank': u'New York Times Building'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'72',
  'Height in feet': u'1,042\xa0ft',
  'Height in meters': u'317\xa0m',
  'Name': u'HHHR Tower',
  'Rank': u'86'},
 {'City': u'Chongqing',
  'Country': u'\xa0China',
  'Floors': u'65',
  'Height in feet': u'1,037\xa0ft',
  'Height in meters': u'316\xa0m',
  'Name': u'Chongqing IFS T1',
  'Rank': u'87'},
 {'City': u'Nanjing',
  'Country': u'\xa0China',
  'Floors': u'68',
  'Height in feet': u'1,032\xa0ft',
  'Height in meters': u'315\xa0m',
  'Name': u'Nanjing International Youth Cultural Centre Tower 1[18]',
  'Rank': u'88'},
 {'City': u'Changsha',
  'Country': u'\xa0China',
  'Floors': u'65',
  'Height in feet': u'1,032\xa0ft',
  'Height in meters': u'315\xa0m',
  'Name': u'Changsha IFS Tower T2',
  'Rank': u'Changsha IFS Tower T2'},
 {'City': u'Bangkok',
  'Country': u'\xa0Thailand',
  'Floors': u'75',
  'Height in feet': u'1,031\xa0ft',
  'Height in meters': u'314\xa0m',
  'Name': u'MahaNakhon',
  'Rank': u'90'},
 {'City': u'Atlanta',
  'Country': u'\xa0United States',
  'Floors': u'55',
  'Height in feet': u'1,024\xa0ft',
  'Height in meters': u'312\xa0m',
  'Name': u'Bank of America Plaza',
  'Rank': u'91'},
 {'City': u'Shenyang',
  'Country': u'\xa0China',
  'Floors': u'75',
  'Height in feet': u'1,020\xa0ft',
  'Height in meters': u'311\xa0m',
  'Name': u'Moi Center',
  'Rank': u'92'},
 {'City': u'Los Angeles',
  'Country': u'\xa0United States',
  'Floors': u'73',
  'Height in feet': u'1,018\xa0ft',
  'Height in meters': u'310\xa0m',
  'Name': u'U.S. Bank Tower',
  'Rank': u'93'},
 {'City': u'Kuala Lumpur',
  'Country': u'\xa0Malaysia',
  'Floors': u'55',
  'Height in feet': u'1,017\xa0ft',
  'Height in meters': u'310\xa0m',
  'Name': u'Menara Telekom',
  'Rank': u'94'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'82',
  'Height in feet': u'1,017\xa0ft',
  'Height in meters': u'310\xa0m',
  'Name': u'Ocean Heights',
  'Rank': u'Ocean Heights'},
 {'City': u'Guangzhou',
  'Country': u'\xa0China',
  'Floors': u'71',
  'Height in feet': u'1,016\xa0ft',
  'Height in meters': u'310\xa0m',
  'Name': u'Pearl River Tower',
  'Rank': u'96'},
 {'City': u'Guangzhou',
  'Country': u'\xa0China',
  'Floors': u'68',
  'Height in feet': u'1,015\xa0ft',
  'Height in meters': u'309\xa0m',
  'Name': u'Fortune Center',
  'Rank': u'97'},
 {'City': u'Dubai',
  'Country': u'\xa0UAE',
  'Floors': u'56',
  'Height in feet': u'1,014\xa0ft',
  'Height in meters': u'309\xa0m',
  'Name': u'Jumeirah Emirates Towers Hotel',
  'Rank': u'98'},
 {'City': u'Moscow',
  'Country': u'\xa0Russia',
  'Floors': u'72',
  'Height in feet': u'1,013\xa0ft',
  'Height in meters': u'309\xa0m',
  'Name': u'Stalnaya Vershina',
  'Rank': u'99'},
 {'City': u'Riyadh',
  'Country': u'\xa0Saudi Arabia',
  'Floors': u'68',
  'Height in feet': u'1,010\xa0ft',
  'Height in meters': u'308\xa0m',
  'Name': u'Burj Rafal',
  'Rank': u'100'},
 {'City': u'Kunming',
  'Country': u'\xa0China',

In [6]:
# clean up a few things
listyx = []
for x in tallest['Height in feet']:
    listyx += [x.split('[')[0]]
tallest['Height in feet'] = listyx

In [7]:
#tallest.index = [i+1 for i in tallest.index]
tallest

,City,Country,Floors,Height in feet,Name
0,Dubai,UAE,163,"2,717 ft",Burj Khalifa
1,Shanghai,China,128,"2,073 ft",Shanghai Tower
2,Mecca,Saudi Arabia,120,"1,971 ft",Abraj Al-Bait Clock Tower
3,Shenzhen,China,115,"1,969 ft",Ping An Finance Centre
4,Seoul,South Korea,123,"1,823 ft",Lotte World Tower
5,New York City,United States,104,"1,776 ft",One World Trade Center
6,Guangzhou,China,111,"1,740 ft",CTF Finance Centre
7,Taipei,Taiwan,101,"1,670 ft",Taipei 101
8,Shanghai,China,101,"1,614 ft",Shanghai World Financial Center
9,Hong Kong,Hong Kong,118,"1,588 ft",International Commerce Centre
10,Kuala Lumpur,Malaysia,88,"1,483 ft",Petronas Tower 1
11,Kuala Lumpur,Malaysia,88,"1,483 ft",Petronas Tower 2
12,Nanjing,China,89,"1,476 ft",Zifeng Tower
13,Chicago,United States,108,"1,451 ft",Willis Tower (formerly the Sears Tower)
14,Shenzhen,China,100,"1,449 ft",KK100
15,Guangzhou,China,103,"1,440 ft",Guangzhou International Finance Center
16,Wuhan,China,88,"1,437 ft",Wuhan Center
17,Dubai,UAE,101,"1,399 ft",Marina 101
18,New York City,United States,88,"1,397 ft",432 Park Avenue
19,Chicago,United States,98,"1,389 ft",Trump International Hotel and Tower[14]
20,Shanghai,China,88,"1,380 ft",Jin Mao Tower
21,Dubai,UAE,101,"1,358 ft",Princess Tower
22,Kuwait City,Kuwait,80,"1,354 ft",Al Hamra Tower
23,Hong Kong,Hong Kong,88,"1,352 ft",Two International Finance Centre
24,Dubai,UAE,89,"1,296 ft",23 Marina
25,Guangzhou,China,80,"1,283 ft",CITIC Plaza
26,Riyadh,Saudi Arabia,77,"1,263 ft",cma tower
27,Shenzhen,China,69,"1,260 ft",Shun Hing Square
28,Dalian,China,81,"1,257 ft",Eton Place Dalian Tower 1
29,Abu Dhabi,UAE,88,"1,251 ft",Burj Mohammed bin Rashid
...,...,...,...,...,...
103,Chicago,United States,60,"1,007 ft",Franklin Center
104,Dubai,UAE,76,"1,005 ft",Cayan Tower
105,New York City,United States,75,"1,004 ft",One57
106,Shenzhen,China,85,"1,004 ft",East Pacific Center Tower A
107,London,United Kingdom,73,"1,004 ft",The Shard
108,Houston,United States,75,"1,002 ft",JPMorgan Chase Tower
109,Abu Dhabi,UAE,79,"1,002 ft",Etihad Tower 2[21][22]
110,Incheon,South Korea,68,"1,001 ft",Northeast Asia Trade Tower
111,Bangkok,Thailand,85,997 ft,Baiyoke Tower II
112,Wuxi,China,68,997 ft,Wuxi Maoye City - Marriott Hotel
113,Shenzhen,China,68,997 ft,Shenzhen CFC Changfu Centre
114,Chicago,United States,64,995 ft,Two Prudential Plaza
115,Liuzhou,China,75,994 ft,Diwang International Fortune Center
116,Riyadh,Saudi Arabia,67,994 ft,KAFD World Trade Center[23]
117,Nanchang,China,59,994 ft,Jiangxi Nanchang Greenland Central Plaza 1[24]
118,Nanchang,China,59,994 ft,Jiangxi Nanchang Greenland Central Plaza 2[25]
119,Jinan,China,60,994 ft,Greenland Puli Center[26]
120,Guangzhou,China,65,993 ft,Leatop Plaza
121,Houston,United States,71,992 ft,Wells Fargo Plaza
122,Riyadh,Saudi Arabia,41,992 ft,Kingdom Centre
123,Dubai,UAE,63,991 ft,The Address Downtown Burj Khalifa
124,Suzhou,China,68,990 ft,Gate of the Orient
125,Moscow,Russia,76,989 ft,Moscow Tower
126,Busan,South Korea,80,984 ft,We've the Zenith Tower A
127,Changsha,China,66,984 ft,Huachuang International Plaza[27]
128,Shenzhen,China,61,987 ft,Shenzhen Zhongzhou Holdings Financial Center T...
129,Santiago,Chile,62,984 ft,Gran Torre Santiago
130,Osaka,Japan,60,984 ft,Abeno Harukas
131,Kuwait City,Kuwait,60,984 ft,Arraya 2
132,Doha,Qatar,36,984 ft,Aspire Tower

## Now it's time to make our new mongodb document! Let's insert our wiki table's values into it.

In [8]:
#Creating a new table with the name table_name here
tallest_building = db.tallest

#This removes everything from the table. Works on the same principle as find
tallest_building.remove({})

#To insert, just pass in the values one at a time
#for x in tallest_building.iterrows():
#    tallest_building.insert_one(x[1].to_dict())
[tallest_building.insert_one(i) for i in listy]

/Users/dnay/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.

[<pymongo.results.InsertOneResult at 0x10c50b280>,
 <pymongo.results.InsertOneResult at 0x10c50b140>,
 <pymongo.results.InsertOneResult at 0x10c50b370>,
 <pymongo.results.InsertOneResult at 0x10c50b640>,
 <pymongo.results.InsertOneResult at 0x10c50b5a0>,
 <pymongo.results.InsertOneResult at 0x10f2eed20>,
 <pymongo.results.InsertOneResult at 0x10f2eeaf0>,
 <pymongo.results.InsertOneResult at 0x10f2eef00>,
 <pymongo.results.InsertOneResult at 0x10f2eeeb0>,
 <pymongo.results.InsertOneResult at 0x10f2eefa0>,
 <pymongo.results.InsertOneResult at 0x10f2eef50>,
 <pymongo.results.InsertOneResult at 0x10f2eee60>,
 <pymongo.results.InsertOneResult at 0x10f2eee10>,
 <pymongo.results.InsertOneResult at 0x10f2eea50>,
 <pymongo.results.InsertOneResult at 0x10c532960>,
 <pymongo.results.InsertOneResult at 0x10c532910>,
 <pymongo.results.InsertOneResult at 0x10c532d20>,
 <pymongo.results.InsertOneResult at 0x10c532a50>,
 <pymongo.results.InsertOneResult at 0x10c532b90>,
 <pymongo.results.InsertOneResult at 0x10c532aa0>,
 <pymongo.results.InsertOneResult at 0x10c532a00>,
 <pymongo.results.InsertOneResult at 0x10c5329b0>,
 <pymongo.results.InsertOneResult at 0x10c532cd0>,
 <pymongo.results.InsertOneResult at 0x10c532d70>,
 <pymongo.results.InsertOneResult at 0x10c532af0>,
 <pymongo.results.InsertOneResult at 0x10c532dc0>,
 <pymongo.results.InsertOneResult at 0x10c532e60>,
 <pymongo.results.InsertOneResult at 0x10c532e10>,
 <pymongo.results.InsertOneResult at 0x10c532eb0>,
 <pymongo.results.InsertOneResult at 0x10c532f00>,
 <pymongo.results.InsertOneResult at 0x10c532f50>,
 <pymongo.results.InsertOneResult at 0x10c52b050>,
 <pymongo.results.InsertOneResult at 0x10c532fa0>,
 <pymongo.results.InsertOneResult at 0x10c52b0a0>,
 <pymongo.results.InsertOneResult at 0x10c52b0f0>,
 <pymongo.results.InsertOneResult at 0x10c52b140>,
 <pymongo.results.InsertOneResult at 0x10c52b190>,
 <pymongo.results.InsertOneResult at 0x10c52b1e0>,
 <pymongo.results.InsertOneResult at 0x10c52b230>,
 <pymongo.results.InsertOneResult at 0x10c52b280>,
 <pymongo.results.InsertOneResult at 0x10c52b2d0>,
 <pymongo.results.InsertOneResult at 0x10c52b320>,
 <pymongo.results.InsertOneResult at 0x10c52b370>,
 <pymongo.results.InsertOneResult at 0x10c52b3c0>,
 <pymongo.results.InsertOneResult at 0x10c52b410>,
 <pymongo.results.InsertOneResult at 0x10c52b460>,
 <pymongo.results.InsertOneResult at 0x10c52b4b0>,
 <pymongo.results.InsertOneResult at 0x10c52b500>,
 <pymongo.results.InsertOneResult at 0x10c52b550>,
 <pymongo.results.InsertOneResult at 0x10c52b5a0>,
 <pymongo.results.InsertOneResult at 0x10c52b5f0>,
 <pymongo.results.InsertOneResult at 0x10c52b640>,
 <pymongo.results.InsertOneResult at 0x10c52b690>,
 <pymongo.results.InsertOneResult at 0x10c52b6e0>,
 <pymongo.results.InsertOneResult at 0x10c52b730>,
 <pymongo.results.InsertOneResult at 0x10c52b780>,
 <pymongo.results.InsertOneResult at 0x10c52b7d0>,
 <pymongo.results.InsertOneResult at 0x10c52b820>,
 <pymongo.results.InsertOneResult at 0x10c52b870>,
 <pymongo.results.InsertOneResult at 0x10c52b8c0>,
 <pymongo.results.InsertOneResult at 0x10c52b910>,
 <pymongo.results.InsertOneResult at 0x10c52b960>,
 <pymongo.results.InsertOneResult at 0x10c52b9b0>,
 <pymongo.results.InsertOneResult at 0x10c52ba00>,
 <pymongo.results.InsertOneResult at 0x10c52ba50>,
 <pymongo.results.InsertOneResult at 0x10c52baa0>,
 <pymongo.results.InsertOneResult at 0x10c52baf0>,
 <pymongo.results.InsertOneResult at 0x10c52bb40>,
 <pymongo.results.InsertOneResult at 0x10c52bb90>,
 <pymongo.results.InsertOneResult at 0x10c52bbe0>,
 <pymongo.results.InsertOneResult at 0x10c52bc30>,
 <pymongo.results.InsertOneResult at 0x10c52bc80>,
 <pymongo.results.InsertOneResult at 0x10c52bcd0>,
 <pymongo.results.InsertOneResult at 0x10c52bd20>,
 <pymongo.results.InsertOneResult at 0x10c52bd70>,
 <pymongo.results.InsertOneResult at 0x10c52bdc0>,
 <pymongo.results.InsertOneResult at 0x10c52be10>,
 <pymongo.results.InsertOneResult at 0x10c52be60>,
 <pymongo.results.InsertOneResult at 0x10c52beb0>,
 <pymongo.results.InsertOneResult at 0x10c52bf00>,
 <pymongo.results.InsertOneResult at 0x10c52bf50>,
 <pymongo.results.InsertOneResult at 0x10c52bfa0>,
 <pymongo.results.InsertOneResult at 0x10c537050>,
 <pymongo.results.InsertOneResult at 0x10c5370a0>,
 <pymongo.results.InsertOneResult at 0x10c5370f0>,
 <pymongo.results.InsertOneResult at 0x10c537140>,
 <pymongo.results.InsertOneResult at 0x10c537190>,
 <pymongo.results.InsertOneResult at 0x10c5371e0>,
 <pymongo.results.InsertOneResult at 0x10c537230>,
 <pymongo.results.InsertOneResult at 0x10c537280>,
 <pymongo.results.InsertOneResult at 0x10c5372d0>,
 <pymongo.results.InsertOneResult at 0x10c537320>,
 <pymongo.results.InsertOneResult at 0x10c537370>,
 <pymongo.results.InsertOneResult at 0x10c5373c0>,
 <pymongo.results.InsertOneResult at 0x10c537410>,
 <pymongo.results.InsertOneResult at 0x10c537460>,
 <pymongo.results.InsertOneResult at 0x10c532c80>,
 <pymongo.results.InsertOneResult at 0x10c532be0>,
 <pymongo.results.InsertOneResult at 0x10c532b40>,
 <pymongo.results.InsertOneResult at 0x10c532c30>,
 <pymongo.results.InsertOneResult at 0x10f2eecd0>,
 <pymongo.results.InsertOneResult at 0x10f2ee960>,
 <pymongo.results.InsertOneResult at 0x10f2ee8c0>,
 <pymongo.results.InsertOneResult at 0x10f2ee910>,
 <pymongo.results.InsertOneResult at 0x10c36b0f0>,
 <pymongo.results.InsertOneResult at 0x10c36b140>,
 <pymongo.results.InsertOneResult at 0x10c5374b0>,
 <pymongo.results.InsertOneResult at 0x10c537500>,
 <pymongo.results.InsertOneResult at 0x10c537550>,
 <pymongo.results.InsertOneResult at 0x10c5375a0>,
 <pymongo.results.InsertOneResult at 0x10c5375f0>,
 <pymongo.results.InsertOneResult at 0x10c537640>,
 <pymongo.results.InsertOneResult at 0x10c537690>,
 <pymongo.results.InsertOneResult at 0x10c5376e0>,
 <pymongo.results.InsertOneResult at 0x10c537730>,
 <pymongo.results.InsertOneResult at 0x10c537780>,
 <pymongo.results.InsertOneResult at 0x10c5377d0>,
 <pymongo.results.InsertOneResult at 0x10c537820>,
 <pymongo.results.InsertOneResult at 0x10c537870>,
 <pymongo.results.InsertOneResult at 0x10c5378c0>,
 <pymongo.results.InsertOneResult at 0x10c537910>,
 <pymongo.results.InsertOneResult at 0x10c537960>,
 <pymongo.results.InsertOneResult at 0x10c5379b0>,
 <pymongo.results.InsertOneResult at 0x10c537a00>,
 <pymongo.results.InsertOneResult at 0x10c537a50>,
 <pymongo.results.InsertOneResult at 0x10c537aa0>,
 <pymongo.results.InsertOneResult at 0x10c537af0>,
 <pymongo.results.InsertOneResult at 0x10c537b40>,
 <pymongo.results.InsertOneResult at 0x10c537be0>,
 <pymongo.results.InsertOneResult at 0x10c537c30>,
 <pymongo.results.InsertOneResult at 0x10c537b90>,
 <pymongo.results.InsertOneResult at 0x10c537c80>,
 <pymongo.results.InsertOneResult at 0x10c537cd0>]

## Awesome! Now find the read-only user in your mongolab account. You are going to be passing this to your partner in the class. Don't be shy. Everyone has to do it.

In [9]:
# Pass your string to another student. 
# Don't forget to change the username and password to your other user's username and password!
# Here is a reminder of what that string looks like
"mongodb://guest:password@ds031925.mlab.com:31925/naytest"

'mongodb://guest:password@ds031925.mlab.com:31925/naytest'

## Open the database you received from your partner. What is the data telling you? What kind of job roles would you imagine dealing with this data?

In [10]:
#This is the client. Replace my (username) and (password) with your non-readonly username and password
client2 = MongoClient("mongodb://guest:abc123@ds031617.mlab.com:31617/cmydata")
#We get the database here. Don't forget to change the db name to your database name!
db = client2.cmydata
hair = db.hair

## Was the data cleaned before you got it? Is information missing that might keep you from figuring out what the data represents?

In [11]:
def printTables(db):
    collection = db.collection_names(include_system_collections=False)
    for collect in collection:
        print collect

In [12]:
hairstyles = []
desc = []
for h in hair.find({}):
    hairstyles += [h['Hairstyle']]
    desc += [h['Description']]

In [13]:
print hairstyles
print desc

[u'Natural', u'Payot', u'Perm', u'Pigtails', u'Pixie cut', u'Queue', u'The Rachel', u'Rattail', u'Razor cut', u'Regular haircut', u'Shag', u'Shingle bob', u'Short back and sides', u'Short brush cut', u'Short hair', u'Slicked-back', u'Spiky hair', u'Tail On Back', u'Tonsure', u'Updo', u'Waves', u'Wings', u'Afro', u'Asymmetric cut', u'Beehive', u'Bettie Page', u'Blow Out', u'Blunt cut', u'Bob cut', u'Bouffant', u'Bowl cut', u'Braid', u'Brush cut', u'Bun', u'Bunches', u'Burr', u'Business-man cut', u'Butch cut', u'Buzz cut', u'Caesar cut', u'Chignon', u'Chonmage', u'Comb over', u'Conk', u'Cornrows', u'Crew cut', u'Cropped hair', u'Crown braid', u'Croydon facelift', u'Curtained hair', u'Devilock', u'Dice Bob', u'Dido flip', u'Dreadlocks', u'Donald Trump hairdo', u"Duck's Ass or D.A.", u'Eton crop', u'Emo hair', u'Fade', u'Fallera hairdo', u'Fauxhawk', u'Feathered hair', u'Finger wave', u'Fishtail hair', u'Flattop', u'Flipped hair', u'Fontange', u'French braid', u'French twist', u'Fringe (bangs)', u'Frosted tips', u'Full crown', u'G.I. haircut', u'Hair extensions', u'Half crown', u'Half updo or Half Up, Half Down', u'Harvard clip', u'Hair with headband', u'High and tight', u'Highlights', u'Hime cut', u'Historical Christian hairstyles', u'Hi-top fade', u'Induction cut', u'Ivy League', u'Jewfro', u'Jheri curl', u'Layered hair', u'Liberty spikes', u'Line up', u'Long hair', u'Marcelling', u'Mod cut', u'Mohawk', u'Mop-Top', u'Mullet', u'Odango', u'Oseledets', u'Pageboy', u'Part', u'Pompadour', u'Ponyhawk', u'Ponytail', u'Princeton', u'Professional cut', u'Psychobilly Wedge', u'Quiff', u'Recon', u'Regular taper cut', u'Ringlets', u'Shape-Up', u'Standard haircut', u'Surfer hair', u'Taper cut', u'Undercut', u'Big hair']

In [16]:
df_hair = pd.DataFrame([i for i in hair.find({})])
df_hair.head()

,Description,Hairstyle,_id
0,A typical texture of Black African hair that h...,Natural,580fae4cfd904fa985a02b26
1,"Sidelocks or earlocks, worn by some males in t...",Payot,580fae4dfd904fa985a02b2b
2,Hair that is chemically treated to retain curl...,Perm,580fae4dfd904fa985a02b2c
3,Hair that is parted into sections or into just...,Pigtails,580fae4dfd904fa985a02b2d
4,A short wispy women's hairstyle with or withou...,Pixie cut,580fae4dfd904fa985a02b2e

## Do some exploratory data analysis on the table. Did you find anything surprising?

In [ ]:
# deal with n/a
tallest = tallest.ix[tallest['Floors'] != 'N/A']
tallest['Floors'] = [float(i) for i in tallest['Floors']]

## Come up with three solvable questions to ask your partner regarding his data. Each should test your knowledge of regular expressions and mongodb. Feel free to look up new ways to do things. Put the questions and the answers to those questions here.

In [23]:
#Question 1: How many hairstyles are longer than 7 letters
listy = []
for idx, i in enumerate(hair.find({'Hairstyle': {'$regex' : '^\w{8}'}})):
    listy.append(idx+1)
listy[-1]

27

In [24]:
#Question 2: How many hairstyles are 2 or more words?
listy = []
for idx, i in enumerate(hair.find({'Hairstyle': {'$regex' : '^\W*\w+\s{1}\w+\W*$'}})):
    listy.append(idx+1)
listy[-1]

54

In [26]:
#Question 3: Which hairstlyes start with the letter 'B'
listy = []
for i in (hair.find({'Hairstyle' : {'$regex' : '^B.*'}})):
    print i['Hairstyle']

Beehive
Bettie Page
Blow Out
Blunt cut
Bob cut
Bouffant
Bowl cut
Braid
Brush cut
Bun
Bunches
Burr
Business-man cut
Butch cut
Buzz cut
Big hair

## Solve the questions your partner gave to you. This is for helping you to get more acquianted with these concepts, so try not to give away your answers.

In [17]:
#question 1
# What is the average number of floors for a building in this list?
import numpy as np
np.mean(tallest['Floors'])

77.37878787878788

In [19]:
#question 2
# How many of the builidings are in the United States?
listy = []
for idx, i in enumerate(tallest_building.find({'Country': {'$regex' : 'States$'}})):
    listy.append(idx+1)
listy[-1]

19

In [20]:
#question 3
# How many buildings are over 1,000 ft?
listy = []
for idx, i in enumerate(tallest_building.find({'Height in feet': {'$regex' : '.*[0-9]{1},.*'}})):
    listy.append(idx+1)
listy[-1]

111

## Try inserting a document into your partner's database. What happens? Why do you think that is?

No bueno, it fails. I don't have write access, only read